In [5]:
import pandas as pd

In [6]:
data_FN = 'data.csv'
data_df = pd.read_csv(data_FN, index_col=0, dtype={'stock_id':str})

In [7]:
data_df.head()

,stock_id,ROE,RealizedVolatility_3M,EBIT2EV,ILLIQ,InvTurnover,OCFGrowth_YOY,AmountVol_1M_12M,ProfitGrowth_Qr_YOY,AssetTurnover,...,NetMargin,EP_FY1,CGO_3M,CFP_TTM,MaxRet,MR,EquityGrowth_YOY,EP2_TTM,ROIC,return
date,,,,,,,,,,,,,,,,,,,,,
20090630,000002,0.1310,0.0279,0.0483,3.42212,0.17716,3.5949,1.4888,0.07050,0.3588,...,0.0955,3.6145,0.1194,0.0362,0.0969,15.432,0.0823,0.0293,0.0973,0.232688
20090630,000006,0.0255,0.0332,0.0095,19.68400,0.17716,0.5792,1.2839,-0.73090,0.2001,...,0.0136,4.3216,0.1194,-0.0575,0.0821,14.416,0.0010,0.0029,0.0083,0.167348
20090630,000012,0.0627,0.0327,0.0230,4.38850,1.95110,1.2827,2.0421,-0.68680,0.4067,...,0.0683,4.0335,-0.0844,0.0608,0.0272,14.667,0.1000,0.0130,0.0184,-0.131858
20090630,000021,0.0842,0.0340,0.0263,12.86900,6.38140,1.0858,2.2975,-0.42840,1.6913,...,0.0239,3.1594,0.1194,0.0364,0.0571,14.613,0.0010,0.0268,0.0916,0.035819
20090630,000024,0.1180,0.0327,0.0244,6.58880,0.17716,1.0687,2.1200,2.80814,0.2001,...,0.3178,3.1311,0.1194,-0.0449,0.0672,15.231,0.8986,0.0253,0.0498,0.146248

In [8]:
data_df['return'].describe()

count    83913.000000
mean         0.011382
std          0.107120
min         -0.176942
25%         -0.063277
50%          0.003736
75%          0.079294
max          0.232688
Name: return, dtype: float64

## set label for classification

In [9]:
high_quantile = 0.80
low_quantile = 0.20

In [10]:
data_df['return'].quantile(high_quantile)

0.10113297846763324

In [11]:
data_df['return'].quantile(low_quantile)

-0.08059679345145285

In [12]:
def set_label_3(x, high, low):
    if x > high:
        return 0 # å¤š
    elif x < low:
        return 2 # ç©º
    else:
        return 1 # æ³¢åŠ¨

In [13]:
high = data_df['return'].quantile(high_quantile)
low = data_df['return'].quantile(low_quantile)
data_df['label_3'] = data_df['return'].apply(lambda x: set_label_3(x, high, low))

In [14]:
data_df.head()

,stock_id,ROE,RealizedVolatility_3M,EBIT2EV,ILLIQ,InvTurnover,OCFGrowth_YOY,AmountVol_1M_12M,ProfitGrowth_Qr_YOY,AssetTurnover,...,EP_FY1,CGO_3M,CFP_TTM,MaxRet,MR,EquityGrowth_YOY,EP2_TTM,ROIC,return,label_3
date,,,,,,,,,,,,,,,,,,,,,
20090630,000002,0.1310,0.0279,0.0483,3.42212,0.17716,3.5949,1.4888,0.07050,0.3588,...,3.6145,0.1194,0.0362,0.0969,15.432,0.0823,0.0293,0.0973,0.232688,0
20090630,000006,0.0255,0.0332,0.0095,19.68400,0.17716,0.5792,1.2839,-0.73090,0.2001,...,4.3216,0.1194,-0.0575,0.0821,14.416,0.0010,0.0029,0.0083,0.167348,0
20090630,000012,0.0627,0.0327,0.0230,4.38850,1.95110,1.2827,2.0421,-0.68680,0.4067,...,4.0335,-0.0844,0.0608,0.0272,14.667,0.1000,0.0130,0.0184,-0.131858,2
20090630,000021,0.0842,0.0340,0.0263,12.86900,6.38140,1.0858,2.2975,-0.42840,1.6913,...,3.1594,0.1194,0.0364,0.0571,14.613,0.0010,0.0268,0.0916,0.035819,1
20090630,000024,0.1180,0.0327,0.0244,6.58880,0.17716,1.0687,2.1200,2.80814,0.2001,...,3.1311,0.1194,-0.0449,0.0672,15.231,0.8986,0.0253,0.0498,0.146248,0

In [15]:
def set_label_2(x):
    if x > 0:
        return 0 # å¤š
    else:
        return 1 # ç©º

In [16]:
data_df['label_2'] = data_df['return'].apply(lambda x: set_label_2(x))

In [17]:
data_df.head()

,stock_id,ROE,RealizedVolatility_3M,EBIT2EV,ILLIQ,InvTurnover,OCFGrowth_YOY,AmountVol_1M_12M,ProfitGrowth_Qr_YOY,AssetTurnover,...,CGO_3M,CFP_TTM,MaxRet,MR,EquityGrowth_YOY,EP2_TTM,ROIC,return,label_3,label_2
date,,,,,,,,,,,,,,,,,,,,,
20090630,000002,0.1310,0.0279,0.0483,3.42212,0.17716,3.5949,1.4888,0.07050,0.3588,...,0.1194,0.0362,0.0969,15.432,0.0823,0.0293,0.0973,0.232688,0,0
20090630,000006,0.0255,0.0332,0.0095,19.68400,0.17716,0.5792,1.2839,-0.73090,0.2001,...,0.1194,-0.0575,0.0821,14.416,0.0010,0.0029,0.0083,0.167348,0,0
20090630,000012,0.0627,0.0327,0.0230,4.38850,1.95110,1.2827,2.0421,-0.68680,0.4067,...,-0.0844,0.0608,0.0272,14.667,0.1000,0.0130,0.0184,-0.131858,2,1
20090630,000021,0.0842,0.0340,0.0263,12.86900,6.38140,1.0858,2.2975,-0.42840,1.6913,...,0.1194,0.0364,0.0571,14.613,0.0010,0.0268,0.0916,0.035819,1,0
20090630,000024,0.1180,0.0327,0.0244,6.58880,0.17716,1.0687,2.1200,2.80814,0.2001,...,0.1194,-0.0449,0.0672,15.231,0.8986,0.0253,0.0498,0.146248,0,0

In [18]:
data_df.to_csv('data.csv', index=False)

In [23]:
for i in range()
data_df.columns.values

AttributeError: 'numpy.ndarray' object has no attribute 'find'

In [26]:
data_df.columns.shape[0]

48

In [27]:
data_df.columns[0]

'stock_id'

In [28]:
find_id = -1
for i in range(data_df.columns.shape[0]):
    if data_df.columns[i] == 'return':
        find_id = i # update

In [29]:
find_id

45

In [30]:
feature_column = list(data_df.columns[2:find_id])

In [32]:
len(feature_column)

43

In [33]:
feature_column

['RealizedVolatility_3M',
 'EBIT2EV',
 'ILLIQ',
 'InvTurnover',
 'OCFGrowth_YOY',
 'AmountVol_1M_12M',
 'ProfitGrowth_Qr_YOY',
 'AssetTurnover',
 'EP_TTM',
 'DISP',
 'Momentumave1M',
 'Momentumlast6M',
 'WFR',
 'ROA',
 'TPER',
 'GP2Asset',
 'SalesGrowth_Qr_YOY',
 'Momentumlast12M',
 'RealizedVolatility_1Y',
 'PPReversal',
 'SCORE',
 'IRFF',
 'Ret1M',
 'Sales2EV',
 'Ret3M',
 'PEG_v2',
 'Debt2Asset',
 'GrossMargin',
 'AmountAvg_1M_3M',
 'COV',
 'TO',
 '52-Week High',
 'SP_TTM',
 'BP_LF',
 'NetMargin',
 'EP_FY1',
 'CGO_3M',
 'CFP_TTM',
 'MaxRet',
 'MR',
 'EquityGrowth_YOY',
 'EP2_TTM',
 'ROIC']